---
- name: Fetch OCP versions
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    ocp_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
    ocp_tmp_file: /tmp/ocp-versions.html
    major_versions:
      - "4.21"
      - "4.20"
      - "4.19"
  tasks:
    - name: Fetch URL
      ansible.builtin.get_url:
        url: "{{ ocp_url }}"
        dest: "{{ ocp_tmp_file }}"
        mode: "0644"

    - name: Read file into var
      ansible.builtin.shell: |
        set -o pipefail
        grep -E '<a href="[[:digit:]]+.[[:digit:]]+.[[:digit:]]+.*">' "{{ ocp_tmp_file }}" | \
          sed -e 's/<a href="//' | sed -e 's/\/">//' | awk '{$1=$1};1' | sort --version-sort | \
          grep -w -e "^{{ item }}" | tail -n1
      register: versions_output
      with_items: "{{ major_versions }}"

    - name: Cleanup
      ansible.builtin.shell: rm -f "{{ ocp_tmp_file }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "Major version [{{ item.item }}]: {{ item.stdout }}"
      with_items: "{{ versions_output.results }}"
      loop_control:
        label: "{{ item.item }}"
