- name: Iteration
  ansible.builtin.debug:
    msg: "Iteration {{ item }}"

- name: Create snapshot of the PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: snapshot.storage.k8s.io/v1
      kind: VolumeSnapshot
      metadata:
        name: "{{ snapshot_name }}-{{ item }}"
        namespace: "{{ namespace }}"
      spec:
        volumeSnapshotClassName: "{{ snapshot_class }}"
        source:
          persistentVolumeClaimName: "{{ original_pvc_name }}"

- name: Wait for VolumeSnapshot to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: VolumeSnapshot
    namespace: "{{ namespace }}"
    name: "{{ snapshot_name }}-{{ item }}"
  register: snap_info
  until: snap_info.resources[0].status.readyToUse
  retries: 20
  delay: 10

- name: Create PVC from snapshot
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ cloned_pvc_name }}-{{ item }}"
        namespace: "{{ namespace }}"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ volume_size }}"
        storageClassName: "{{ storage_class }}"
        dataSource:
          name: "{{ snapshot_name }}-{{ item }}"
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
